<?php
/**
 * Netresearch_OPS_Block_Form_OpsId
 *
 * @category  design
 * @package   OPS
 * @copyright 2012 Netresearch App Factory AG <http://www.netresearch.de>
 * @author    Thomas Birke <thomas.birke@netresearch.de>
 * @license   OSL 3.0
 */
?>
<?php $this->getParams(); ?>
<script type="text/javascript">
    Translator.add(
        'Account number must contain numbers only.',
        '<?php echo Mage::helper('ops')->__('Account number must contain numbers only.') ?>'
    );
    Translator.add(
        'Bank code must contain numbers only.',
        '<?php echo Mage::helper('ops')->__('Bank code must contain numbers only.') ?>'
    );
    Translator.add(
        'Payment failed. Please select another payment method.',
        '<?php echo Mage::helper('ops')->__('Payment failed. Please select another payment method.') ?>'
    );
    Translator.add(
        'This is a required field.',
        '<?php echo Mage::helper('ops')->__('This is a required field.') ?>'
    );
</script>

<ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none">
    <li>
        <label class="required" for="ops_directdebit_country_id"><?php echo $this->__('Country'); ?></label><br/>
        <select title="ops_directdebit_country_id" class="required-entry" name="ops_directdebit_country_id"
                id="ops_directdebit_country_id" onchange="payment.toggleOpsDirectDebitInputs(this.value)">
            <option value=""><?php echo $this->__('--Please Select--') ?></option>
            <?php foreach ($this->getDirectDebitCountryIds() as $countryId) : ?>
                <option value="<?php echo $countryId; ?>"><?php echo Mage::getModel('directory/country')->loadByCode(
                        $countryId
                    )->getName(); ?></option>
            <?php endforeach; ?>
        </select>
    </li>
    <li>
        <label class="required" for="ops_directdebit_CN"><?php echo $this->__('Account holder'); ?></label><br/>
        <input title="CN" class="input-text required-entry" autocomplete="off" type="text" name="CN"
               id="ops_directdebit_CN" length="50"
               value="<?php echo $this->getQuote()->getBillingAddress()->getFirstname() . ' ' . $this->getQuote()
                       ->getBillingAddress()->getLastname() ?>"/>
    </li>
    <li>
        <label class="required" for="ops_directdebit_iban"><?php echo $this->__('IBAN'); ?></label><br/>
        <input title="IBAN" class="input-text required-entry" autocomplete="off" type="text" name="iban"
               id="ops_directdebit_iban" onblur="payment.setRequiredDirectDebitFields(this);"/>
    </li>
    <li style="display:none">
        <label class="" for="ops_directdebit_bic"><?php echo $this->__('BIC'); ?></label><br/>
        <input class="input-text" title="BIC" type="text" name="bic" id="ops_directdebit_bic"
               onblur="payment.setRequiredDirectDebitFields(this);"/>
    </li>
    <li>
        <label class="required" for="ops_directdebit_account_no"><?php echo $this->__('Account number'); ?></label><br/>
        <input title="account_no" class="input-text required-entry validate-number validate-length maximum-length-11"
               onblur="payment.setRequiredDirectDebitFields(this);" autocomplete="off" type="text" name="account_no"
               id="ops_directdebit_account_no" maxlength="11"/>
    </li>
    <li style="display:none">
        <label class="required" for="ops_directdebit_bank_code"><?php echo $this->__('Bank code'); ?></label><br/>
        <input class="input-text required-entry" type="text" name="bank_code"
               onblur="payment.setRequiredDirectDebitFields(this);" id="ops_directdebit_bank_code" maxlength="8"/>
    </li>

    <script type="text/javascript">
        opsDirectDebitUrl = '<?php echo $this->getRegisterDirectDebitPaymentUrl() ?>';
    </script>
</ul>